#!/bin/sh
TMPDIR=`mktemp -d`

# TODO: separate logic for gcc and g++ (separete env for LIBRARY_PATH?)
echo '#include <stdio.h>' | gcc -v -x c -E - 2> $TMPDIR/gcc > /dev/null

while read line
do
  if [ -n "$START" ]; then
    if [ "$line" = "End of search list." ]; then
      START=
    elif [ -n "$ZIGWRAPPER_CPATH" ]; then
      ZIGWRAPPER_CPATH="$ZIGWRAPPER_CPATH:$line"
    else
      ZIGWRAPPER_CPATH="$line"
    fi
  elif [ "$line" = "#include <...> search starts here:" ]; then
    START=yes
  elif [ "${line%${line#????????????}}" = "LIBRARY_PATH" ]; then
    libpath="$line"
  fi
done < $TMPDIR/gcc
rm -rf $TMPDIR
export $libpath ZIGWRAPPER_CPATH="$ZIGWRAPPER_CPATH"
exec "$@"
