#!/bin/sh
ZIGWRAPPER_LIBC_VERSION=$1
shift
export CPPFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0"
ZIGWRAPPER_LIBC_VERSION=$ZIGWRAPPER_LIBC_VERSION CC=$(dirname $0)/zig_cc_wrapper_x86_64-linux-gnu CXX=$(dirname $0)/zig_c++_wrapper_x86_64-linux-gnu $(dirname $0)/zig_set_path "$@"
